### ISSUE TITLE
error in test_gen_basinElevationBands testing

### ISSUE THREAD

**Issue by tonyewong** [hydrosolutions/riversCentralAsia#100]
Looks like the more detailed error I see both when running devtools::test() or source("testthat.R") from the tests directory is the following:
```
══ Failed tests ══════════════════════════════════════════════════════════════════════
── Error (test_gen_basinElevationBands.R:9): Elevation bands are correctly generated ──
Error in `Ops.units(size_fxn(singles), threshold)`: both operands of the expression should be "units" objects
Backtrace:
    ▆
 1. └─riversCentralAsia::gen_basinElevationBands(...) at test_gen_basinElevationBands.R:9:2
 2.   ├─smoothr::drop_crumbs(...) at riversCentralAsia/R/gen_basinElevationBands.R:60:2
 3.   └─smoothr:::drop_crumbs.sf(...)
 4.     ├─smoothr::drop_crumbs(...)
 5.     └─smoothr:::drop_crumbs.sfc(...)
 6.       ├─singles[size_fxn(singles) >= threshold]
 7.       ├─sf:::`[.sfc`(singles, size_fxn(singles) >= threshold)
 8.       └─units:::Ops.units(size_fxn(singles), threshold)
── Error (test_gen_basinElevationBands.R:21): Can read dem from raster object ──
Error in `Ops.units(size_fxn(singles), threshold)`: both operands of the expression should be "units" objects
Backtrace:
    ▆
 1. └─riversCentralAsia::gen_basinElevationBands(...) at test_gen_basinElevationBands.R:21:2
 2.   ├─smoothr::drop_crumbs(...) at riversCentralAsia/R/gen_basinElevationBands.R:60:2
 3.   └─smoothr:::drop_crumbs.sf(...)
 4.     ├─smoothr::drop_crumbs(...)
 5.     └─smoothr:::drop_crumbs.sfc(...)
 6.       ├─singles[size_fxn(singles) >= threshold]
 7.       ├─sf:::`[.sfc`(singles, size_fxn(singles) >= threshold)
 8.       └─units:::Ops.units(size_fxn(singles), threshold)

[ FAIL 2 | WARN 0 | SKIP 1 | PASS 78 ]
```

Relatedly, I'd suggest just adding a line or two to the README.md to indicate how users ought to test their installs. I got the previous error by running some of the contents of the testthat.R script interactively. Pointing folks straight to devtools::test() would be an easy way to go.

**Comment by mabesa** [comment]
Thank you. I am running devtools::test() now and see many new warnings I'll have to deal with (regarding the latest version of the tidyselect package).  None of the tests fail on my system so currently, I cannot reproduce the error messages you get. 

I'll uninstall all the dependencies of the package to see, if this leads me to the problem.

**Comment by mabesa** [comment]
I hope I solved the problems in the test suite. Here is what I did: 

Uninstalling all dependencies and then running devtools::test() in the project folder worked, I was able to reproduce the problem. Apparently the raster package does no longer support a crs format I used. 

Tested a fresh install of riversCentralAsia and successfully tested it with my real-life data sets. 

I also added a description in the README of how the package may be tested (I'm no package testing expert, please let me know if there is a better way to do this). 

I'll keep this thread open until we're sure the tests now also run on your system.

**Comment by tonyewong** [comment]
Looks good! Tests are all passing on my system now. I'll close the issue.
