### ISSUE TITLE
Documentation/Statement of Need

### ISSUE THREAD

**Issue by tonyewong** [hydrosolutions/riversCentralAsia#102]
Can it be clarified raw data types are supported, and what form the processed data takes? This could be valuable to mention in at least one of the paper, the top-level README.md file, or the documentation Github Pages site.

**Comment by mabesa** [comment]
A very good idea. I have written a vignette article on this and will add a sentence on this in the README as well. I'll probably have to update the paper too. 
I have trouble rendering the Github Pages though and am waiting for input from the package maintainer.

**Comment by mabesa** [comment]
The deployment issue is solved and the documentation adapted, I hope more or less understandable. Thank you for the suggestion.
