### ISSUE TITLE
Software Paper Review

### ISSUE THREAD

**Issue by mengqi-z** [hydrosolutions/riversCentralAsia#116]
Hi @mabesa,

I have few feedback on the software paper for JOSS https://github.com/openjournals/joss-reviews/issues/4805

1. Title - the title misleads the reader to believe this package performs some sort of hydrological modeling. However, the package mainly facilitates data preparation and processing. Please refine the title to reflect the package's actual functionality.

2. Line 8 - please be consistent and use either "modelling" or "modeling", not both.

3. Statement of need
- The second paragraph in "statement of need" states the data preparation steps. However, it includes steps that are not actually done in the `riversCentralAsia` package, which could mislead readers on the package functionality. For example, I believe "delineation of river catchment boundaries" is processed in QGIS. Please revise the paragraph and focus on what functions this package can deliver.
- The third paragraph in "statement of need" is great material for data availability, but it does not extend to how the package is needed to process those data. I would suggest adding one or two sentences to highlight the ease-to-use feature of the package to process those datasets.
- Line 41 mentioned down-scaling of ERA5 re-analysis data. I think this is pointing to `doQuantileMapping` function. I am not quite sure if this function fits the concept of  "downscaling" because the function is more like bias-correction. Also, downscaling can include spatial and temporal downscaling.

4. Installation - could you include the R version (>= 4.1) requirement for this package? Or at least add this requirement to the Github Page.

5. Figure 1 - some abbreviations are not explained in the figure or paper (e.g., GSM).

**Comment by mabesa** [comment]
Thanks a lot for your critical review. This improves the paper so much!
1. Title is adapted and should reflect the data processing focus of the package now
2. consistent use of modelling
3. Adapting statement of need  
- I tried to more clearly state which components of the modelling workflow are covered by the package. 
- A good point. I added examples of how the package supports the use of this data. 
- quantile mapping is indeed a bias correction algorithm but it is used for statistical downscaling. I added a sentence on this and an appropriate reference. 
4. Added R >= 4.1 under installation
5. Added a bracket and links for GSM and HBV

**Comment by mengqi-z** [comment]
Hi @mabesa,

Thank you for addressing my comments. I read through the latest version of the paper and I think it improved a lot. Some minor typos I noticed in the paper:

1. Line 2: there should be a space between "pre-" and "and".
2. Line 21: "touse" should be "to use".
3. Line 28: add "includes" after "package"?

I may not capture every typo. I suggest carefully read through the paper to make sure there are no typos and everything reads good. Thank you.

**Comment by mabesa** [comment]
Thank you, I got the notification and found yet another couple of typos! I'm sure there will be more, I've read the text about 4 times today and still I find spelling errors.
