### ISSUE TITLE
Add Examples of Functions for "Preparation for Climate Forcing"

### ISSUE THREAD

**Issue by mengqi-z** [hydrosolutions/riversCentralAsia#123]
Hi @mabesa,

The instructions in the section [Preparation of climate forcing](https://hydrosolutions.github.io/riversCentralAsia/articles/02-preparation-of-climate-forcing.html) only talk about the `gen_basinElevationBands` function and don't mention much about how `riversCentralAsia` can help prepare climate forcing data, which is a major functionality claimed in the paper. I understand there might be difficulties due to the large size of the CHELSA dataset. Could a simple demo example be added for the usage of the major functions for preparing climate forcing data, such as `biasCorrect_ERA5_CHELSA`, `generate_ERA5_Subbasin_CSV`, etc.? I cannot find the usage of those functions in the book [Modeling of Hydrological Systems in Semi-Arid Central Asia](https://hydrosolutions.github.io/caham_book/) neither.

It would be helpful to mention in this instruction that for advanced user, they can find more details on functions related to climate forcing preparation in this specific section [Downscaling and Bias Correction Using Quantile Mapping](https://hydrosolutions.github.io/caham_book/climate_data.html#sec-bcds-quantile-mapping).

https://github.com/openjournals/joss-reviews/issues/4805

**Comment by mabesa** [comment]
Dear @mengqi-z 
My colleague had time for testing and I added 2 examples in the Preparation of climate forcing instructions. I also referred to the chapter in the online book which gives detailed step-by-step instructions of how to use the functions in the workflow. 

The two functions biasCorrect_ERA5_CHELSA and generate_ERA5_Subbasin_CSV were obsolete and removed from the package.
