### ISSUE TITLE
downloading the package riverCentralAsia

### ISSUE THREAD

**Issue by Agnerol** [hydrosolutions/riversCentralAsia#125]
Hello,
I'm doing my Bachelor Thesis and I'm using the course book [Modeling of Hydrological Systems in Semi-Arid Central Asia](https://hydrosolutions.github.io/caham_book/) (Siegfried & Marti, 2022).

I tried installing the riverCentralAsia Package, and even if I did download and load every packages I still get, when I do devtools::test():
[ FAIL 0 | WARN 5 | SKIP 0 | PASS 93 ]

Is it bad that WARN ist on 5 and PASS ist on 93?
How could I solve it or is it fine like that?
Best regards,
Agnes

**Comment by mabesa** [comment]
Hi Agnes

It should be ok if none of the tests fail. Do you want to send me the warnings that you get so I can check if it is anything suspicious? 

Greetings, 
Beatrice

**Comment by Agnerol** [comment]
1. Warning: recordingTimeStep = 2292000 is currently not implemented.

2. Warning (test_load_minerve_input_csv.R:2:3): Loading the test file works
 2917 failed to parse.

3. Warning (test_load_minerve_input_csv.R:8:3): Loading the glacier forcing test file works
 2917 failed to parse.

4. Warning (test_readDBCSV.R:3:3): Loading the test file works
 2917 failed to parse.
 
 5. Warning (test_readDBCSV.R:16:3): Loading the other test file works
 33 failed to parse.
 
 6. Warning (test_readDBCSV.R:27:3): Loading the glacier forcing test file works
 2917 failed to parse.

**Comment by Agnerol** [comment]
Should I post it with the Backtrace?

**Comment by mabesa** [comment]
I checked: 
Warning 1 is ok, it's printed by a test function that gets a recordingTimeStep which is not implemented.

Warnings 2 and 3 and similarly warnings 4 and 5 should not occur. Please check how the file https://github.com/hydrosolutions/riversCentralAsia/blob/master/tests/testthat/hepler_test_load_minerve_input_csv.csv is formatted on your computer, especially the date format (it should be in the format %02d.%02m.%y %H:%M) 

edit: feel free to let me know if you run into issues. I'd also be interested to learn where you study and what your model goal is.

**Comment by mabesa** [comment]
@Agnerol do you have an update on the issue?

**Comment by Agnerol** [comment]
hey @mabesa 
I couldn't find the solution so I just continued with the course. 
Everything worked out except the test.
Also do you know where I can find stations data? I wanted to do an hydrological analysis of the area above the Toktogul.

**Comment by mabesa** [comment]
Hi @Agnerol, glad to hear that the rest of the course worked fine for you!
Please contact me via marti@hydrosolutions.ch. There are several options to obtain station data, I'll elaborate. Please add a description of your study project.
