### ISSUE TITLE
couldn't download the example data set

### ISSUE THREAD

**Issue by Ruslan161296** [hydrosolutions/riversCentralAsia#88]
![image](https://user-images.githubusercontent.com/102782763/161198175-dd8111e2-3b1e-497a-8017-1bbb04530af1.png)
hello, i wanted to repeat all flows of modeling, but i have stopped, because can not download training data set, link for downloading is incorrect

**Comment by mabesa** [comment]
Thank you for reporting the issue. 
That is an issue in the caham book (https://github.com/hydrosolutions/caham_book). The link is updated and the book will be re-rendered with the new updates shortly.
